### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sorjor-net** [AMalininHere/camunda-worker-dotnet#21] opened 2020-12-03 10:27 UTC
Hi, 

It seems like we have discovered a memory leak when using the Camunda Worker package.
According to dotMemory we are building up types of:
* CancellationTokenSource
* HttpClient
* ExternalTaskClient
It slowly grows over time, with the rate increasing under load.

It seems to be caused by the way ExternalTaskClient is resolved inside ExternalTaskContext.

According to 
https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container
the container will hold onto these references forever.

Maybe the calls to GetRequiredService<T> should be inside its own scope. I am not sure if transient services will be released on scope exit.

Have you noticed anything similar?

I will continue the investigation.

**Comment by sorjor-net** [comment] 2020-12-03 14:41
Simply removing the inheritance from IDisposable in IExternalTaskClient seems to remove the leaks of the mentioned object types.
As mentioned in the link above:
> When you register Transient services that implement IDisposable, by default the DI container will hold onto these references, and not Dispose() of them until the application stops.

According to https://www.stevejgordon.co.uk/httpclient-creation-and-disposal-internals-should-i-dispose-of-httpclient it doesn't seem to be a big violation of some rule to skip disposing HttpClient objects..
> Answer when using HttpClientFactory:
> 
> There is no need to dispose of the HttpClient instances from HttpClientFactory. Disposal will not actually do anything in this case because the factory manages the handler and connection lifetimes and not the HttpClient instances. Calling dispose on HttpClient has no effect for instances provided by the factory and is simply redundant code.

**Comment by AMalininHere** [comment] 2020-12-03 19:00
Hello,

Thank you for your feedback and the investigation!
I tried to reproduce described problem and I had seen that obtaining of `IExternalTaskClient` from root service provider really leads to memory leaks. The problem has more to do with `ExternalTaskSelector` (used in root scope) also uses `IExternalTaskClient`.

**Comment by AMalininHere** [comment] 2020-12-03 19:31
@sorjor-net the problem is resolved in [0.10.2](https://github.com/AMalininHere/camunda-worker-dotnet/releases/tag/0.10.2)

**Closed by AMalininHere** 2020-12-03 19:31 UTC
Labels: bug
